<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Digital_wallet extends MAIN_Controller implements AdminModuleLoader
{

    public function __construct()
    {
        parent::__construct();
        $this->init('digital_wallet');
    }

    public function onLoad()
    {
        parent::onLoad(); // TODO: Change the autogenerated stub

        define('DIGITAL_WALLET_SEND_RECEIVE', 'digital_wallet_send_receive');

        $this->load->model("digital_wallet/wallet_model", 'mWalletModel');
    }


    public function onCommitted($isEnabled)
    {


        if(!$isEnabled && !ModulesChecker::isEnabled("payment"))
            return;


        //setup payment for waller
        $payment_redirection = site_url("payment/make_payment");
        $payment_callback_success = site_url("payment/wallet_payment_confirm");
        $payment_callback_error = site_url("payment/payment_error");


        $payments = PaymentsProvider::getPayments("default");


        PaymentsProvider::provide("wallet",$payments,
            $payment_redirection,
            $payment_callback_success,
            $payment_callback_error
        );

        PaymentsProvider::excludePayments('wallet',array(PaymentsProvider::WALLET_ID,PaymentsProvider::COD_ID));

        //disable taxes
        TaxManager::disable('wallet');


    }


    private function setupWalletPayments(){


    }




    public function onInstall()
    {
        return TRUE;
    }

    public function onUpgrade()
    {

        GroupAccess::registerActions("digital_wallet", array(
            DIGITAL_WALLET_SEND_RECEIVE
        ));

        return TRUE;
    }

    public function onEnable()
    {

        GroupAccess::registerActions("digital_wallet", array(
            DIGITAL_WALLET_SEND_RECEIVE
        ));


        return TRUE;
    }


    public function onAdminLoaded($module)
    {
        /*
         * return bool / function
         */

        return function (){



        };
    }
}