<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Booking extends MAIN_Controller implements AdminModuleLoader
{

    const MODULE_NAME = "booking";

    public function __construct()
    {
        parent::__construct();
        $this->init('booking');
    }

    public function onLoad()
    {
        $this->load->model("booking/Booking_model", "mBookingModel");
        $this->load->helper("booking/booking");

        define('GRP_MANAGE_MY_BOOKING','manage_my_booking');
        define('GRP_MANAGE_BOOKING','manage_booking');
        define('GRP_MANAGE_BOOKING_CONFIG','manage_booking_config');
    }


    public function onCommitted($isEnabled)
    {
        if(!$isEnabled)
            return;

        //register module menu
        AdminTemplateManager::registerMenu(
            Booking::MODULE_NAME,
            "booking/menu",
            3
        );


    }


    public function onEnable()
    {

        GroupAccess::registerActions(Booking::MODULE_NAME,array(
            GRP_MANAGE_BOOKING,
            GRP_MANAGE_BOOKING_CONFIG
        ));


        return TRUE;
    }

    public function onUpgrade()
    {
        parent::onUpgrade(); // TODO: Change the autogenerated stub

        /*
         * Update field in the database
         */
        $this->mBookingModel->create_table();
        $this->mBookingModel->update_fields();

        /*
         * Register new word
         */
        Translate::updateLanguages("booking");


        GroupAccess::reloadActions(Booking::MODULE_NAME,array(
            GRP_MANAGE_BOOKING,
            GRP_MANAGE_BOOKING_CONFIG
        ));

        return TRUE;
    }


    public function onInstall()
    {
        parent::onInstall(); // TODO: Change the autogenerated stub

        $this->mBookingModel->create_table();
        $this->mBookingModel->update_fields();

        /*
        * Register new word
        */
        Translate::updateLanguages("booking");



        return TRUE;
    }



    public function onAdminLoaded($module)
    {
        /*
         * return bool / function
         */

        if(!ModulesChecker::isEnabled("booking")){
            return false;
        }

        return function (){
            //create dashboard widget for booking
            $this->mBookingModel->createDashboardWidget();
        };
    }

}